// frontend/components/layout/Footer.tsx
"use client";

import { Separator } from "@/components/ui/separator";

export function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="border-t bg-background">
      <div className="container flex h-16 items-center justify-between px-4">
        <div className="flex items-center gap-4 text-sm text-muted-foreground">
          <span>© {currentYear} Gestão Financeira</span>
          <Separator orientation="vertical" className="h-4" />
          <span>Todos os direitos reservados</span>
        </div>
        <div className="flex items-center gap-4 text-sm text-muted-foreground">
          <a href="#" className="hover:text-foreground">
            Sobre
          </a>
          <Separator orientation="vertical" className="h-4" />
          <a href="#" className="hover:text-foreground">
            Contato
          </a>
        </div>
      </div>
    </footer>
  );
}

// frontend/src/components/layout/Footer.vue
<template>
  <footer class="border-t bg-white py-4">
    <div class="mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex flex-col items-center justify-between gap-4 sm:flex-row">
        <p class="text-sm text-gray-600">
          © {{ currentYear }} Gestão Financeira. Todos os direitos reservados.
        </p>
        <div class="flex items-center gap-4 text-sm text-gray-600">
          <span>Versão {{ appVersion }}</span>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { env } from '@/config/env'

const currentYear = computed(() => new Date().getFullYear())
const appVersion = computed(() => env.appVersion)
</script>
