// frontend/src/components/TransactionTable.vue
<template>
  <Card>
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Data</TableHead>
          <TableHead>Descrição</TableHead>
          <TableHead>Tipo</TableHead>
          <TableHead>Valor</TableHead>
          <TableHead>Conta</TableHead>
          <TableHead class="text-right">Ações</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow
          v-for="transaction in transactions"
          :key="transaction.transaction_id"
          class="hover:bg-muted/50 transition-colors"
        >
          <TableCell class="whitespace-nowrap">
            {{ formatDate(transaction.date) }}
          </TableCell>
          <TableCell>
            <div class="max-w-xs truncate" :title="transaction.description">
              {{ transaction.description }}
            </div>
          </TableCell>
          <TableCell class="whitespace-nowrap">
            <Badge
              :variant="transaction.type === 'INCOME' ? 'default' : 'destructive'"
              class="bg-green-100 text-green-800 hover:bg-green-100"
              v-if="transaction.type === 'INCOME'"
            >
              Receita
            </Badge>
            <Badge
              variant="destructive"
              class="bg-red-100 text-red-800 hover:bg-red-100"
              v-else
            >
              Despesa
            </Badge>
          </TableCell>
          <TableCell
            class="whitespace-nowrap font-medium"
            :class="transaction.type === 'INCOME' ? 'text-green-600' : 'text-red-600'"
          >
            {{ formatCurrency(parseFloat(transaction.amount)) }}
          </TableCell>
          <TableCell class="whitespace-nowrap text-muted-foreground">
            {{ getAccountName(transaction.account_id) }}
          </TableCell>
          <TableCell class="text-right">
            <Button variant="link" as-child>
              <router-link :to="`/transactions/${transaction.transaction_id}`">
                Ver detalhes
              </router-link>
            </Button>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>

    <!-- Empty State -->
    <div
      v-if="transactions.length === 0"
      class="px-6 py-12 text-center"
    >
      <Inbox class="mx-auto h-12 w-12 text-muted-foreground mb-4" />
      <p class="text-muted-foreground">Nenhuma transação encontrada</p>
    </div>
  </Card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useAccountsStore } from '@/stores/accounts'
import { Card } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Inbox } from 'lucide-vue-next'
import type { Transaction } from '@/api/types'

interface Props {
  transactions: Transaction[]
}

const props = defineProps<Props>()

const accountsStore = useAccountsStore()

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(value)
}

function formatDate(dateString: string): string {
  if (!dateString) return 'Data inválida'
  
  const date = new Date(dateString)
  
  if (isNaN(date.getTime())) {
    console.warn('[TransactionTable] Data inválida:', dateString)
    return 'Data inválida'
  }
  
  return new Intl.DateTimeFormat('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  }).format(date)
}

function getAccountName(accountId: string): string {
  const account = accountsStore.accounts.find((acc) => acc.account_id === accountId)
  return account?.name || 'Conta não encontrada'
}
</script>

// frontend/components/transactions/TransactionTable.tsx
"use client";

import Link from "next/link";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import type { Transaction } from "@/lib/api/types";
import { cn } from "@/lib/utils";

interface TransactionTableProps {
  transactions: Transaction[];
  className?: string;
}

/**
 * Formata um valor monetário
 */
function formatCurrency(value: string, currency: string = "BRL"): string {
  const numValue = parseFloat(value);
  if (isNaN(numValue)) {
    return `R$ 0,00`;
  }

  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: currency === "BRL" ? "BRL" : currency === "USD" ? "USD" : "EUR",
  }).format(numValue);
}

/**
 * Formata uma data
 */
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

/**
 * Mapeia o tipo de transação para um label e cor
 */
const transactionTypeConfig: Record<Transaction["type"], { label: string; color: string }> = {
  INCOME: { label: "Receita", color: "text-green-600 dark:text-green-400" },
  EXPENSE: { label: "Despesa", color: "text-red-600 dark:text-red-400" },
};

/**
 * Componente de tabela para exibir transações
 */
export function TransactionTable({ transactions, className }: TransactionTableProps) {
  if (transactions.length === 0) {
    return (
      <div className={cn("text-center py-12 text-muted-foreground", className)}>
        <p>Nenhuma transação encontrada</p>
      </div>
    );
  }

  return (
    <div className={cn("rounded-md border", className)}>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Data</TableHead>
            <TableHead>Descrição</TableHead>
            <TableHead>Tipo</TableHead>
            <TableHead className="text-right">Valor</TableHead>
            <TableHead className="text-right">Ações</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {transactions.map((transaction) => {
            const typeConfig = transactionTypeConfig[transaction.type];
            const amount = formatCurrency(transaction.amount, transaction.currency);
            const isIncome = transaction.type === "INCOME";

            return (
              <TableRow key={transaction.transaction_id}>
                <TableCell className="font-medium">
                  {formatDate(transaction.date)}
                </TableCell>
                <TableCell>{transaction.description}</TableCell>
                <TableCell>
                  <span className={typeConfig.color}>{typeConfig.label}</span>
                </TableCell>
                <TableCell className={cn("text-right font-semibold", typeConfig.color)}>
                  {isIncome ? "+" : "-"} {amount}
                </TableCell>
                <TableCell className="text-right">
                  <Link href={`/transactions/${transaction.transaction_id}`}>
                    <Button variant="ghost" size="sm">
                      Ver Detalhes
                    </Button>
                  </Link>
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}
