// frontend/src/components/TransactionForm.vue
<template>
  <Form
    @submit="handleSubmit"
    :validation-schema="validationSchema"
    :initial-values="initialValues"
    v-slot="{ errors }"
  >
    <Card v-if="error" class="mb-4 border-destructive">
      <CardContent class="p-3">
        <div class="flex items-center gap-2">
          <AlertCircle class="h-4 w-4 text-destructive" />
          <p class="text-sm text-destructive">{{ error }}</p>
        </div>
      </CardContent>
    </Card>

    <div class="space-y-6">
      <!-- Conta -->
      <div>
        <Label for="account_id" class="mb-1">
          Conta <span class="text-destructive">*</span>
        </Label>
        <Field
          id="account_id"
          name="account_id"
          as="select"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
          :class="errors.account_id ? 'border-destructive' : ''"
          :disabled="isLoading"
        >
          <option value="">Selecione uma conta</option>
          <option
            v-for="account in accounts"
            :key="account.account_id"
            :value="account.account_id"
          >
            {{ account.name }} ({{ account.currency }})
          </option>
        </Field>
        <ErrorMessage name="account_id" class="mt-1 text-sm text-destructive" />
      </div>

      <!-- Tipo -->
      <div>
        <Label for="type" class="mb-1">
          Tipo <span class="text-destructive">*</span>
        </Label>
        <Field
          id="type"
          name="type"
          as="select"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
          :class="errors.type ? 'border-destructive' : ''"
          :disabled="isLoading"
        >
          <option value="">Selecione o tipo</option>
          <option value="INCOME">Receita</option>
          <option value="EXPENSE">Despesa</option>
        </Field>
        <ErrorMessage name="type" class="mt-1 text-sm text-destructive" />
      </div>

      <!-- Valor -->
      <div>
        <Label for="amount" class="mb-1">
          Valor <span class="text-destructive">*</span>
        </Label>
        <Field
          id="amount"
          name="amount"
          type="number"
          step="0.01"
          min="0.01"
          as-child
        >
          <Input
            :class="errors.amount ? 'border-destructive' : ''"
            placeholder="0.00"
            :disabled="isLoading"
          />
        </Field>
        <ErrorMessage name="amount" class="mt-1 text-sm text-destructive" />
      </div>

      <!-- Moeda -->
      <div>
        <Label for="currency" class="mb-1">
          Moeda <span class="text-destructive">*</span>
        </Label>
        <Field
          id="currency"
          name="currency"
          as="select"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
          :class="errors.currency ? 'border-destructive' : ''"
          :disabled="isLoading"
        >
          <option value="BRL">BRL - Real Brasileiro</option>
          <option value="USD">USD - Dólar Americano</option>
          <option value="EUR">EUR - Euro</option>
        </Field>
        <ErrorMessage name="currency" class="mt-1 text-sm text-destructive" />
      </div>

      <!-- Descrição -->
      <div>
        <Label for="description" class="mb-1">
          Descrição <span class="text-destructive">*</span>
        </Label>
        <Field
          id="description"
          name="description"
          as-child
        >
          <Textarea
            :class="errors.description ? 'border-destructive' : ''"
            placeholder="Descreva a transação..."
            :disabled="isLoading"
            rows="3"
          />
        </Field>
        <p class="mt-1 text-xs text-muted-foreground">
          Mínimo 3 caracteres, máximo 500 caracteres
        </p>
        <ErrorMessage name="description" class="mt-1 text-sm text-destructive" />
      </div>

      <!-- Data -->
      <div>
        <Label for="date" class="mb-1">
          Data <span class="text-destructive">*</span>
        </Label>
        <Field
          id="date"
          name="date"
          type="date"
          as-child
        >
          <Input
            :class="errors.date ? 'border-destructive' : ''"
            :disabled="isLoading"
          />
        </Field>
        <p class="mt-1 text-xs text-muted-foreground">
          Data da transação (formato: YYYY-MM-DD)
        </p>
        <ErrorMessage name="date" class="mt-1 text-sm text-destructive" />
      </div>

      <!-- Actions Slot -->
      <slot name="actions" :isLoading="isLoading" :errors="errors">
        <div class="flex gap-3 pt-4">
          <Button
            type="submit"
            :disabled="isLoading"
          >
            <Loader2 v-if="isLoading" class="h-4 w-4 animate-spin" />
            <Check v-else class="h-4 w-4" />
            {{ submitLabel || 'Salvar' }}
          </Button>
        </div>
      </slot>
    </div>
  </Form>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Form, Field, ErrorMessage } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { createTransactionSchema } from '@/validations/transaction'
import { useAccountsStore } from '@/stores/accounts'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { AlertCircle, Loader2, Check } from 'lucide-vue-next'
import type { CreateTransactionFormData } from '@/validations/transaction'

interface Props {
  initialValues?: Partial<CreateTransactionFormData>
  submitLabel?: string
  isLoading?: boolean
}

interface Emits {
  (e: 'submit', values: CreateTransactionFormData): void
}

const props = withDefaults(defineProps<Props>(), {
  isLoading: false,
  submitLabel: 'Salvar',
})

const emit = defineEmits<Emits>()

const accountsStore = useAccountsStore()

const validationSchema = toTypedSchema(createTransactionSchema)
const error = ref<string | null>(null)

const accounts = computed(() => accountsStore.accounts)

function handleSubmit(values: any) {
  error.value = null
  emit('submit', values as CreateTransactionFormData)
}

function setError(message: string) {
  error.value = message
}

function clearError() {
  error.value = null
}

defineExpose({
  setError,
  clearError,
})
</script>

// frontend/components/transactions/TransactionForm.tsx
"use client";

import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ErrorDisplay } from "@/components/auth";
import { LoadingSpinner } from "@/components/auth";
import { useAccounts } from "@/lib/hooks/useAccounts";
import type { CreateTransactionRequest } from "@/lib/api/types";
import { cn } from "@/lib/utils";

const transactionFormSchema = z.object({
  account_id: z.string().min(1, "Selecione uma conta"),
  type: z.enum(["INCOME", "EXPENSE"]).refine((val) => val !== undefined, {
    message: "Selecione um tipo de transação",
  }),
  amount: z
    .string()
    .min(1, "Valor é obrigatório")
    .refine(
      (val) => {
        const num = parseFloat(val);
        return !isNaN(num) && num > 0;
      },
      {
        message: "Valor deve ser um número positivo",
      }
    ),
  currency: z.enum(["BRL", "USD", "EUR"]).refine((val) => val !== undefined, {
    message: "Selecione uma moeda",
  }),
  description: z.string().min(3, "Descrição deve ter no mínimo 3 caracteres").max(500, "Descrição deve ter no máximo 500 caracteres"),
  date: z.string().min(1, "Data é obrigatória"),
});

type TransactionFormData = z.infer<typeof transactionFormSchema>;

interface TransactionFormProps {
  onSubmit: (data: CreateTransactionRequest) => Promise<void>;
  onCancel?: () => void;
  isLoading?: boolean;
  error?: string | null;
  className?: string;
  defaultAccountId?: string;
}

/**
 * Componente de formulário para criar/editar transação
 * Reutilizável em diferentes contextos (página, modal, etc.)
 */
export function TransactionForm({
  onSubmit,
  onCancel,
  isLoading = false,
  error,
  className,
  defaultAccountId,
}: TransactionFormProps) {
  const { accounts, isLoading: isLoadingAccounts } = useAccounts();
  const [formError, setFormError] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
    watch,
  } = useForm<TransactionFormData>({
    resolver: zodResolver(transactionFormSchema),
    defaultValues: {
      currency: "BRL",
      date: new Date().toISOString().split("T")[0], // Data atual no formato YYYY-MM-DD
      account_id: defaultAccountId || "",
    },
  });

  const typeValue = watch("type");
  const currencyValue = watch("currency");
  const accountIdValue = watch("account_id");

  // Atualizar account_id quando defaultAccountId mudar
  useEffect(() => {
    if (defaultAccountId && !accountIdValue) {
      setValue("account_id", defaultAccountId);
    }
  }, [defaultAccountId, accountIdValue, setValue]);

  const onFormSubmit = async (data: TransactionFormData) => {
    setFormError(null);

    try {
      const transactionData: CreateTransactionRequest = {
        account_id: data.account_id,
        type: data.type,
        amount: data.amount,
        currency: data.currency,
        description: data.description,
        date: data.date,
      };

      await onSubmit(transactionData);
    } catch (err: any) {
      const errorMessage =
        err.response?.data?.error ||
        err.response?.data?.message ||
        err.message ||
        "Erro ao criar transação. Tente novamente.";

      setFormError(errorMessage);
    }
  };

  return (
    <form onSubmit={handleSubmit(onFormSubmit)} className={cn("space-y-6", className)}>
      {(error || formError) && (
        <ErrorDisplay
          error={error || formError || undefined}
        />
      )}

      <div className="space-y-4">
        {/* Conta */}
        <div className="space-y-2">
          <Label htmlFor="account_id">Conta *</Label>
          {isLoadingAccounts ? (
            <div className="flex items-center gap-2">
              <LoadingSpinner />
              <span className="text-sm text-muted-foreground">Carregando contas...</span>
            </div>
          ) : (
            <Select
              value={accountIdValue}
              onValueChange={(value) => setValue("account_id", value)}
              disabled={isLoading || isLoadingAccounts}
            >
              <SelectTrigger id="account_id">
                <SelectValue placeholder="Selecione uma conta" />
              </SelectTrigger>
              <SelectContent>
                {accounts.map((account) => (
                  <SelectItem key={account.account_id} value={account.account_id}>
                    {account.name} ({accountTypeLabels[account.type] || account.type})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          {errors.account_id && (
            <p className="text-sm text-destructive">{errors.account_id.message}</p>
          )}
          {accounts.length === 0 && !isLoadingAccounts && (
            <p className="text-sm text-muted-foreground">
              Nenhuma conta disponível.{" "}
              <a href="/accounts/new" className="text-primary hover:underline">
                Criar conta
              </a>
            </p>
          )}
        </div>

        {/* Tipo de Transação */}
        <div className="space-y-2">
          <Label htmlFor="type">Tipo de Transação *</Label>
          <Select
            value={typeValue}
            onValueChange={(value) => setValue("type", value as TransactionFormData["type"])}
            disabled={isLoading}
          >
            <SelectTrigger id="type">
              <SelectValue placeholder="Selecione o tipo" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="INCOME">Receita</SelectItem>
              <SelectItem value="EXPENSE">Despesa</SelectItem>
            </SelectContent>
          </Select>
          {errors.type && (
            <p className="text-sm text-destructive">{errors.type.message}</p>
          )}
        </div>

        {/* Valor e Moeda */}
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="amount">Valor *</Label>
            <Input
              id="amount"
              type="number"
              step="0.01"
              min="0.01"
              placeholder="0.00"
              {...register("amount")}
              disabled={isLoading}
            />
            {errors.amount && (
              <p className="text-sm text-destructive">{errors.amount.message}</p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="currency">Moeda *</Label>
            <Select
              value={currencyValue}
              onValueChange={(value) => setValue("currency", value as TransactionFormData["currency"])}
              disabled={isLoading}
            >
              <SelectTrigger id="currency">
                <SelectValue placeholder="Selecione a moeda" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="BRL">Real (BRL)</SelectItem>
                <SelectItem value="USD">Dólar (USD)</SelectItem>
                <SelectItem value="EUR">Euro (EUR)</SelectItem>
              </SelectContent>
            </Select>
            {errors.currency && (
              <p className="text-sm text-destructive">{errors.currency.message}</p>
            )}
          </div>
        </div>

        {/* Descrição */}
        <div className="space-y-2">
          <Label htmlFor="description">Descrição *</Label>
          <Textarea
            id="description"
            placeholder="Descreva a transação..."
            {...register("description")}
            disabled={isLoading}
            rows={3}
          />
          {errors.description && (
            <p className="text-sm text-destructive">{errors.description.message}</p>
          )}
          <p className="text-xs text-muted-foreground">
            {watch("description")?.length || 0}/500 caracteres
          </p>
        </div>

        {/* Data */}
        <div className="space-y-2">
          <Label htmlFor="date">Data *</Label>
          <Input
            id="date"
            type="date"
            {...register("date")}
            disabled={isLoading}
          />
          {errors.date && (
            <p className="text-sm text-destructive">{errors.date.message}</p>
          )}
        </div>
      </div>

      {/* Botões */}
      <div className="flex gap-4">
        {onCancel && (
          <Button
            type="button"
            variant="outline"
            onClick={onCancel}
            disabled={isLoading}
            className="flex-1"
          >
            Cancelar
          </Button>
        )}
        <Button type="submit" disabled={isLoading || isLoadingAccounts || accounts.length === 0} className="flex-1">
          {isLoading ? <LoadingSpinner /> : "Criar Transação"}
        </Button>
      </div>
    </form>
  );
}

// Helper para labels de tipo de conta
const accountTypeLabels: Record<string, string> = {
  BANK: "Banco",
  WALLET: "Carteira",
  INVESTMENT: "Investimento",
  CREDIT_CARD: "Cartão",
};
